wandb_version: 1

max_depth:
  desc: null
  value: 20
min_samples_leaf:
  desc: null
  value: 4
min_samples_split:
  desc: null
  value: 7
n_estimators:
  desc: null
  value: 32
_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685708517.495951
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.4
      5: 0.15.3
      8:
      - 4
      - 5
